param(
  [ValidateSet("safe", "balanced", "throughput", "low-latency")]
  [string]$Preset = "balanced",

  [string]$SourcePath,

  [string]$OutPath
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent (Split-Path -Parent $PSCommandPath)

if (-not $SourcePath) {
  $SourcePath = Join-Path $root "config/application.example.yml"
}

if (-not $OutPath) {
  $OutPath = Join-Path $root "config/application.calibrated.yml"
}

$presets = @{
  "safe" = @{
    bufferDurationMs = 2000
    frameBufferDurationMs = 10000
    opusEncodingQuality = 8
    trackStuckThresholdMs = 30000
    playerUpdateInterval = 5
    youtubePlaylistLoadLimit = 8
    playlistLoadLimit = 300
    searchLimit = 10
    tomcatMaxThreads = 128
    requestTimeout = "35s"
    maxInMemorySize = "12MB"
  }
  "balanced" = @{
    bufferDurationMs = 2500
    frameBufferDurationMs = 14000
    opusEncodingQuality = 10
    trackStuckThresholdMs = 30000
    playerUpdateInterval = 5
    youtubePlaylistLoadLimit = 12
    playlistLoadLimit = 1000
    searchLimit = 15
    tomcatMaxThreads = 256
    requestTimeout = "45s"
    maxInMemorySize = "16MB"
  }
  "throughput" = @{
    bufferDurationMs = 3500
    frameBufferDurationMs = 18000
    opusEncodingQuality = 10
    trackStuckThresholdMs = 45000
    playerUpdateInterval = 5
    youtubePlaylistLoadLimit = 18
    playlistLoadLimit = 1500
    searchLimit = 20
    tomcatMaxThreads = 384
    requestTimeout = "60s"
    maxInMemorySize = "24MB"
  }
  "low-latency" = @{
    bufferDurationMs = 1200
    frameBufferDurationMs = 7000
    opusEncodingQuality = 8
    trackStuckThresholdMs = 25000
    playerUpdateInterval = 3
    youtubePlaylistLoadLimit = 8
    playlistLoadLimit = 250
    searchLimit = 8
    tomcatMaxThreads = 192
    requestTimeout = "30s"
    maxInMemorySize = "12MB"
  }
}

$selected = $presets[$Preset]
$content = Get-Content -Raw -Path $SourcePath

function Replace-First {
  param(
    [string]$InputText,
    [string]$Pattern,
    [string]$Replacement
  )

  return [regex]::Replace($InputText, $Pattern, $Replacement, 1)
}

$content = Replace-First $content '(?m)^      max: \d+$' "      max: $($selected.tomcatMaxThreads)"
$content = Replace-First $content '(?m)^      request-timeout: .+$' "      request-timeout: $($selected.requestTimeout)"
$content = Replace-First $content '(?m)^    max-in-memory-size: .+$' "    max-in-memory-size: $($selected.maxInMemorySize)"
$content = Replace-First $content '(?m)^    bufferDurationMs: \d+$' "    bufferDurationMs: $($selected.bufferDurationMs)"
$content = Replace-First $content '(?m)^    frameBufferDurationMs: \d+$' "    frameBufferDurationMs: $($selected.frameBufferDurationMs)"
$content = Replace-First $content '(?m)^    opusEncodingQuality: \d+$' "    opusEncodingQuality: $($selected.opusEncodingQuality)"
$content = Replace-First $content '(?m)^    trackStuckThresholdMs: \d+$' "    trackStuckThresholdMs: $($selected.trackStuckThresholdMs)"
$content = Replace-First $content '(?m)^    playerUpdateInterval: \d+$' "    playerUpdateInterval: $($selected.playerUpdateInterval)"
$content = Replace-First $content '(?m)^    youtubePlaylistLoadLimit: \d+$' "    youtubePlaylistLoadLimit: $($selected.youtubePlaylistLoadLimit)"
$content = Replace-First $content '(?m)^      searchLimit: \d+$' "      searchLimit: $($selected.searchLimit)"
$content = Replace-First $content '(?m)^      playlistLoadLimit: \d+$' "      playlistLoadLimit: $($selected.playlistLoadLimit)"

$header = @"
# Generated by scripts/calibrate-oskarlink.ps1.
# Preset: $Preset
# Source: $SourcePath

"@

Set-Content -Path $OutPath -Value ($header + $content.TrimStart()) -Encoding UTF8
"Wrote $OutPath"
